server:
  port: 8016

spring:
  profiles:
    active: dqy
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  # 配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  thymeleaf:
    cache: false

  # 验证码有效时间/分钟
code:
  expiration: 5

# 上传目录设置
upload:
  path: uploads
  avatar: avatar
  picture: picture

# excel 导出最大行数
excel:
  export-max-count: 100000

#jwt
jwt:
  licence: 1612569600000